version: 0.2

phases:
  install:
    commands:
      - echo "Docker가 사전 설치된 표준 빌드 이미지를 사용합니다."

  pre_build:
    commands:
      - echo "Docker Hub에 로그인합니다..."
      - echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - cd backend/fittoring

  build:
    commands:
      - "echo 'Gradle Wrapper에 실행 권한을 부여합니다...'"
      - "chmod +x ./gradlew"

      - "echo 'Gradle을 사용하여 Jar 파일을 빌드합니다.'"
      - "./gradlew clean"
#      - "./gradlew generateApiDocs"
      - "./gradlew bootJar -x test"
      
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPOSITORY_URI="$DOCKERHUB_USERNAME/fittoring"
      - echo "Docker 이미지 빌드: $IMAGE_TAG"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Docker 이미지 Push"
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "배포용 이미지 태그 저장"
      - echo $IMAGE_TAG > deploysettings/image_tag.txt

      - mkdir -p ../../deploysettings_root
      - cp -r deploysettings/* ../../deploysettings_root/

artifacts:
  base-directory: deploysettings_root
  files:
    - appspec.yml
    - docker-compose.yml
    - image_tag.txt
    - scripts/**/*
