version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: fittoring
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s

  db-test:
    image: mysql:8.0
    container_name: mysql-test-container
    environment:
      MYSQL_DATABASE: fittoring-test
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    container_name: redis-test-container
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  app:
    image: ${IMAGE}:${TAG}
    container_name: fittoring-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "80:8080"
    env_file: .env
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/app/otel-agent.jar"
      OTEL_SERVICE_NAME: fittoring
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=${SPRING_PROFILES_ACTIVE:-prod}"
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_EXPORTER_OTLP_ENDPOINT: ${TEMPO_GRPC_LISTENER_URL}
      OTEL_EXPORTER_OTLP_LOGS_PROTOCOL: http/protobuf
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://monitoring.fittoring.store:8080/otlp/v1/logs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - /home/ssm-user/fittoring/opentelemetry-javaagent.jar:/app/otel-agent.jar:ro
      - /home/ubuntu/fittoring/logs:/logs
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8080/healthcheck | grep -q '\"status\":\"UP\"'" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 120s

volumes:
  db-data:

networks:
  default:
