version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: fittoring
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s

  db-test:
    image: mysql:8.0
    container_name: mysql-test-container
    environment:
      MYSQL_DATABASE: fittoring-test
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "13307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fittoring-app
    depends_on:
      db:
        condition: service_healthy
      db-test:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db-data:
