version: '3.8'

services:
  db-test:
    image: mysql:8.0
    container_name: mysql-test-container
    profiles: ["test"]
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_DATABASE: fittoring-test
      MYSQL_ROOT_PASSWORD: 1234
      LANG: C.UTF-8
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    container_name: redis-test-container
    profiles: ["test"]
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  app:
    image: ${IMAGE}:${TAG}
    container_name: fittoring-app
    mem_limit: 1g
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "80:8080"
    env_file: .env
    environment:
      TZ: Asia/Seoul
      JAVA_TOOL_OPTIONS: "-Xmx512m"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - /home/ubuntu/fittoring/logs:/logs
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8080/healthcheck | grep -q '\"status\":\"UP\"'" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 120s

networks:
  default:
