version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: fittoring
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql

  db-test:
    image: mysql:8.0
    container_name: mysql-test-container
    environment:
      MYSQL_DATABASE: fittoring-test
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: always

volumes:
  db-data:
