version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - |
        if [ "$APP_ENV" = "production" ]; then
          echo "✅ Building for PRODUCTION..."
          npm run build:prod
        elif [ "$APP_ENV" = "development" ]; then
          echo "✅ Building for DEVELOPMENT..."
          npm run build:dev
        else
          echo "❌ Unknown APP_ENV. Halting build."
          exit 1
        fi

artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
