spring:
  datasource:
    url: jdbc:mysql://db:3306/fittoring?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
