spring:
  application:
    name: fittoring
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: optional:file:.env[.properties]
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cloud:
    aws:
      region: ap-northeast-2
      credentials:
        access-key: ${AWS_IAM_ACCESS_KEY}
        secret-key: ${AWS_IAM_SECRET_KEY}

server:
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      # 모든 프록시 주소를 신뢰하도록 설정 (도커/Cloudflare 환경에서 필수)
      internal-proxies: ".*"
      protocol-header: x-forwarded-proto
    use-relative-redirects: true
    threads:
      max: ${TOMCAT_MAX_THREADS}
    max-connections: ${TOMCAT_MAX_CONNECTIONS}
    connection-timeout: ${TOMCAT_CONNECTION_TIMEOUT}
    keep-alive-timeout: ${TOMCAT_KEEP_ALIVE_TIMEOUT}
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: heapdump, health,info,prometheus, metrics
      path-mapping:
        health: healthcheck
        prometheus: prometheus-provider
  endpoint:
    heapdump:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.95,0.99
    tags:
      environment: ${SPRING_PROFILES_ACTIVE}
  prometheus:
    metrics:
      export:
        step: ${METRICS_EXPORT_TIME_TO_PROMETHEUS}
sms:
  base-url: https://api.solapi.com
  timeout:
    connect: 1200
    read: 5000

logging:
  file:
    name: /logs/application.log
  level:
    root: INFO
    fittoring.mentoring: DEBUG
  pattern:
    file: "%msg%n"
    console: "%msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: logs/application.%d{yyyy-MM}.%i.log
      max-history: 2
      max-file-size: 10MB

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-millis: ${ACCESS_TOKEN_EXPIRATION_MILLIS}
  refresh-token-expiration-millis: ${REFRESH_TOKEN_EXPIRATION_MILLIS}

kakao:
  redirect-url: ${KAKAO_REDIRECT_URL}
  client-id: ${KAKAO_CLIENT_ID}

aws:
  s3:
    region: ap-northeast-2
    bucket-name: fittoring-s3
    project-prefix: fit-toring/
  sqs:
    push-notification-queue: fittoring-push-notification-queue
    push-notification-unregistered-tokens-queue: fittoring-push-notification-unregistered-tokens
    chat-message-persist-queue: fittoring-chat-message-persist.fifo

image-session:
  merge:
    enabled: true
    fixed-delay-ms: 300000
    batch-size: 200

domain:
  sub-domain: ${SUB_DOMAIN}

client:
  base-url: ${CLIENT_BASE_URL}
