spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${PROD_DATABASE_HOST}:${PROD_DATABASE_PORT}/${PROD_DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${PROD_DATABASE_USER}
    password: ${PROD_DATABASE_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
sms:
  base-url: https://api.solapi.com
  timeout:
    connect: 1_200
    read: 5_000
logging:
  file:
    name: /logs/application.log
  level:
    root: INFO
    fittoring.mentoring: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: logs/application.%d{yyyy-MM}.%i.log
      max-history: 2
      max-file-size: 10MB
