import type { CommunityPostDetail } from '../../../common/types/communityPost';
import type { PostComment } from '../types/postComment';

export const COMMUNITY_POST_DETAIL: CommunityPostDetail = {
  id: 1,
  title: '게시글 제목',
  content: '게시글 본문',
  nickname: '작성자명',
  isAnonymous: false,
  isGuestPost: false,
  isMine: true,
  createdAt: '2026-04-06T21:30:00',
  viewCount: 100,
  likeCount: 10,
  commentCount: 20,
} as const;

export const POST_COMMENTS: PostComment[] = [
  {
    id: 201,
    content: '루트 댓글',
    nickname: 'user1',
    isAnonymous: false,
    isGuestComment: false,
    rootId: null,
    parentId: null,
    isDeleted: false,
    createdAt: '2026-04-06T21:30:00',
  },
  {
    id: 202,
    content: '대댓글',
    nickname: 'user2',
    isAnonymous: false,
    isGuestComment: true,
    rootId: 201,
    parentId: 201,
    isDeleted: false,
    createdAt: '2026-04-06T21:31:00',
  },
  {
    id: 203,
    content: '저도 참여하고 싶어요.',
    nickname: 'user3',
    isAnonymous: false,
    isGuestComment: false,
    rootId: null,
    parentId: null,
    isDeleted: false,
    createdAt: '2026-04-06T21:34:00',
  },
  {
    id: 204,
    content: '몇 시에 시작하시나요?',
    nickname: '러너A',
    isAnonymous: true,
    isGuestComment: false,
    rootId: 203,
    parentId: 203,
    isDeleted: false,
    createdAt: '2026-04-06T21:35:00',
  },
  {
    id: 205,
    content: '오전 8시쯤 생각하고 있어요.',
    nickname: '작성자명',
    isAnonymous: false,
    isGuestComment: false,
    rootId: 203,
    parentId: 204,
    isDeleted: false,
    createdAt: '2026-04-06T21:36:00',
  },
  {
    id: 206,
    content: '장소는 여의도 한강공원인가요?',
    nickname: 'guest12',
    isAnonymous: false,
    isGuestComment: true,
    rootId: null,
    parentId: null,
    isDeleted: false,
    createdAt: '2026-04-06T21:40:00',
  },
  {
    id: 207,
    content: '네 맞아요. 3번 출구 쪽에서 만나요.',
    nickname: '작성자명',
    isAnonymous: false,
    isGuestComment: false,
    rootId: 206,
    parentId: 206,
    isDeleted: false,
    createdAt: '2026-04-06T21:42:00',
  },
  {
    id: 208,
    content: '삭제된 댓글 예시',
    nickname: 'deletedUser',
    isAnonymous: false,
    isGuestComment: false,
    rootId: null,
    parentId: null,
    isDeleted: true,
    createdAt: '2026-04-06T21:45:00',
  },
] as const;
