export const API_ENDPOINTS = {
  SPECIALTIES: '/categories',
  MENTORINGS: '/mentorings',
  RESERVATION: '/reservation',
  SIGNUP: '/signup',
  VALIDATE_ID: '/validate-id',
  AUTH_CODE: '/auth-code',
  AUTH_CODE_VERIFY: '/auth-code/verify',
  MEMBERS_ME: '/members/me',
  LOGIN: '/login',
  CREATED_MENTORING: '/mentorings/mine/reservations',
  MEMBERS: '/members/summary',
  PATCH_MENTORING_STATUS: '/status',
  MENTEE_PHONE_NUMBER: '/phone',
} as const;
