export const API_ENDPOINTS = {
  SPECIALTIES: '/categories',
  MENTORINGS: '/mentorings',
  RESERVATION: '/reservation',
  RESERVATIONS: '/reservations',
  SIGNUP: '/signup',
  VALIDATE_ID: '/validate-id',
  AUTH_CODE: '/auth-code',
  AUTH_CODE_VERIFY: '/auth-code/verify',
  MEMBERS_ME: '/members/me',
  LOGIN: '/login',
  LOGOUT: '/logout',
  CREATED_MENTORING: '/mentorings/mine/reservations',
  MINE_MENTORING: '/mentorings/mine',
  PARTICIPATED_MENTORING: '/reservations/participated',
  MEMBERS: '/members/summary',
  REISSUE: '/reissue',
  PATCH_MENTORING_STATUS: '/status',
  MENTEE_PHONE_NUMBER: '/phone',
  REVIEWS: '/reviews',
} as const;
