export const PAGE_URL = {
  HOME: '/',
  DETAIL: '/detail',
  BOOKING: '/booking',
  MENTORING_CREATE: '/mentoring-create',
  MENTORING_UPDATE: '/mentoring-update',
  MY_PAGE: '/my-page',
  CREATED_MENTORING: '/my-page/created-mentoring',
  PARTICIPATED_MENTORING: '/my-page/participated-mentoring',
  SIGNUP: '/signup',
  LOGIN: '/login',
  LANDING: '/landing',
  EDIT_PROFILE: '/my-page/edit-profile',
  IDENTITY_VERIFICATION: '/identity-verification',
  CHAT_ROOM: '/chat/room',
} as const;
