export const PAGE_URL = {
  HOME: '/',
  DETAIL: '/detail',
  BOOKING: '/booking',
  MENTORING_CREATE: '/mentoring-create',
  MENTORING_UPDATE: '/mentoring-update',
  MY_PAGE: '/my-page',
  CREATED_MENTORING: '/my-page/created-mentoring',
  PARTICIPATED_MENTORING: '/my-page/participated-mentoring',
  SETTINGS: '/my-page/settings',
  APP_INSTALL_GUIDE: '/my-page/settings/app-install',
  SIGNUP: '/signup',
  LOGIN: '/login',
  LANDING: '/landing',
  EDIT_PROFILE: '/my-page/edit-profile',
  IDENTITY_VERIFICATION: '/identity-verification',
  CHAT_ROOM: '/chat/room',
  CHAT_ROOMS: '/chat/rooms',
  COMMUNITY: '/community',
  COMMUNITY_SEARCH: '/community/search',
  COMMUNITY_SEARCH_RESULT: '/community/search/result',
  EDIT: '/edit',
  COMMUNITY_CREATE: '/community/create',
} as const;
