export type MENTORING_APPLICATION_STATUS =
  | 'APPROVE'
  | 'REJECT'
  | 'PENDING'
  | 'COMPLETE';

export enum MENTORING_APPLICATION_STATUS_ENUM {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  PENDING = 'PENDING',
  COMPLETE = 'COMPLETE',
}
