name: Backend CD

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  backend-cd:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Run deploy script
        run: |
          cd /home/ubuntu
          ./deploy-be.sh