name: Backend CD

on:
  push:
    branches: [ release ]

jobs:
  backend-cd:
    runs-on: self-hosted

    steps:
      - name: Run deploy script
        run: |
          cd /home/ubuntu
          ./deploy-be.sh