name: "frontend-build test"

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "frontend/**"
jobs:
  Build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci # package-lock.json 기반으로 설치 (CI 환경에 권장)
        working-directory: ./frontend # frontend 디렉토리에서 실행

      - name: Generate environment variables
        run: |
          if [[ "${{ github.base_ref }}" == "develop" ]]; then
            echo "✅ Environment: DEVELOPMENT"
            echo "API_BASE_URL=${{ secrets.FE_DEV_API_BASE_URL }}" >> .env.dev
            echo "SENTRY_DSN=${{ secrets.FE_DEV_SENTRY_DSN }}" >> .env.dev
            echo "KAKAO_REDIRECT_URL=${{ secrets.FE_DEV_KAKAO_REDIRECT_URL }}" >> .env.dev
          elif [[ "${{ github.base_ref }}" == "release-dev" || "${{ github.base_ref }}" == "release-prod" ]]; then
            echo "✅ Environment: PRODUCTION"
            echo "API_BASE_URL=${{ secrets.FE_PROD_API_BASE_URL }}" >> .env.prod
            echo "SENTRY_DSN=${{ secrets.FE_PROD_SENTRY_DSN }}" >> .env.prod
            echo "KAKAO_REDIRECT_URL=${{ secrets.FE_PROD_KAKAO_REDIRECT_URL }}" >> .env.prod
          else
            echo "❌ Error: Unsupported target branch for CI."
            exit 1
          fi

          echo "SENTRY_AUTH_TOKEN=${{ secrets.FE_SENTRY_AUTH_TOKEN }}" >> .env
          echo "GOOGLE_ANALYTICS_ID=${{ secrets.FE_GOOGLE_ANALYTICS_ID }}" >> .env
          echo "KAKAO_REST_API_KEY=${{ secrets.FE_KAKAO_REST_API_KEY }}" >> .env
          echo "CHANNEL_TALK_PLUGIN_KEY=${{ secrets.FE_CHANNEL_TALK_PLUGIN_KEY }}" >> .env
        working-directory: ./frontend # frontend 디렉토리에서 실행

      - name: Build for Development
        if: github.base_ref == 'develop'
        run: npm run build:dev
        working-directory: ./frontend

      - name: Build for Production
        if: github.base_ref == 'release-dev' || github.base_ref == 'release-prod'
        run: npm run build:prod
        working-directory: ./frontend
