name: Backend CI/CD

on:
  pull_request:
    branches: [ release-prod ]
    paths: [ 'backend/**' ]
  push:
    branches: [ release-prod ]
    paths: [ 'backend/**' ]
  workflow_dispatch:

jobs:
  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      IMAGE: fittoring/fittoring
    defaults:
      run:
        working-directory: backend/fittoring
    outputs:
      image_tag: ${{ steps.tags.outputs.prod_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('./**/*.gradle*', './**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build jar
        run: |
          chmod +x ./gradlew
          ./gradlew clean generateApiDocs bootJar

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set tags
        id: tags
        run: |
          echo "prod_tag=prod" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: backend/fittoring
          file: backend/fittoring/Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ env.IMAGE }}:${{ steps.tags.outputs.prod_tag }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:cache
          cache-to: type=registry,ref=${{ env.IMAGE }}:cache,mode=max

  deploy-prod:
    needs: build-and-push
    runs-on:
      - self-hosted
      - prod
    env:
      IMAGE: fittoring/fittoring
      TAG: ${{ needs.build-and-push.outputs.image_tag }}
    steps:
      - name: Docker hub login
        run: |
          sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Write .env for deploy
        run: |
          cd /home/ssm-user/fittoring
          sudo sh -c 'echo "IMAGE=${{ env.IMAGE }}" > .env.deploy'
          sudo sh -c 'echo "TAG=${{ env.TAG }}" >> .env.deploy'

      - name: Run deploy script
        run: |
          cd /home/ssm-user
          ./deploy-be.sh
