ALTER TABLE review
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE review
ADD COLUMN deleted_at DATETIME NULL;

ALTER TABLE mentoring
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE mentoring
ADD COLUMN deleted_at DATETIME NULL;

ALTER TABLE reservation
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE reservation
ADD COLUMN deleted_at DATETIME NULL;

ALTER TABLE category_mentoring
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE category_mentoring
ADD COLUMN deleted_at DATETIME NULL;

ALTER TABLE certificate
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE certificate
ADD COLUMN deleted_at DATETIME NULL;

ALTER TABLE member
ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE member
ADD COLUMN deleted_at DATETIME NULL;







